### Write Python Programs to use various operators in Python

In [2]:
a=5
b=10
print("ARITHMETIC OPERATORS")
print("Addition(+)",a+b)
print("Subtraction(-)",a-b)
print("Multiplication(*)",a*b)
print("Division(/)",a/b)
print("Modulus(%)",a%b)
print("Exponent(**)",a**b)
print("FloorDivision(//)",a//b)
print("\n")
print("ASSIGNMENT OPERATORS")
c=10
print("assignment operator(=)",c)
print("\n")
print("COMPARISON OPEARTORS")
print("Equal to (==):",a==b)
print("Not Equal to(!=) :",a!=b)
print("Less than (<):",a<b)
print("Greater than (>):",a>b)
print("Less than or equal to(<=) :",a<=b)
print("Greater than or equal to(>=) :",a>=b)
print("\n")
print("LOGICAL OPEARTORS")
print("and operator(and)",a and b)
print("or operator (or)",a or b)
print("not operator(not)",not a)
print("\n")
print("IDENTITY OPEARTORS")
print("is :",a is True)
print("is not :",b is not True)
print("\n")
print("BITWISE OPEARTORS")
print("& :",a&b)
print("| :",a|b)
print("^ :",a^b)
print("~ :",~b)
print("<< :",a<<b)
print(">> :",a>>b)


ARITHMETIC OPERATORS
Addition(+) 15
Subtraction(-) -5
Multiplication(*) 50
Division(/) 0.5
Modulus(%) 5
Exponent(**) 9765625
FloorDivision(//) 0


ASSIGNMENT OPERATORS
assignment operator(=) 10


COMPARISON OPEARTORS
Equal to (==): False
Not Equal to(!=) : True
Less than (<): True
Greater than (>): False
Less than or equal to(<=) : True
Greater than or equal to(>=) : False


LOGICAL OPEARTORS
and operator(and) 10
or operator (or) 5
not operator(not) False


IDENTITY OPEARTORS
is : False
is not : True


BITWISE OPEARTORS
& : 0
| : 15
^ : 15
~ : -11
<< : 5120
>> : 0


### Create list of elements and slice and dice it

In [4]:
list=[1,22,32,13,7,52]

In [6]:
list[0:5]



[1, 32, 7]

In [7]:
list[:4]


[1, 22, 32, 13]

In [8]:
list[:-1]


[1, 22, 32, 13, 7]

In [9]:
list[0:5:2]

[1, 32, 7]

### . Using while loop accept numbers until sum of numbers is less than 100

In [18]:
sum=0
diff=0

while sum<100:
    i=int(input("enter the number"))
    diff=100-sum;
    if diff<0:
        break;
    else:
        sum=sum+i;
   
    
print(sum)

enter the number30
enter the number40
enter the number20
enter the number12
102


### Write a python program Read & write Excel files

In [19]:
f = open("demofile.txt", "r")
print(f.read())

Hi,This python demo file


In [20]:
f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()

### Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [22]:
import numpy as np
matrix =  np.arange(2, 11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [ ]:
import numpy as np

list1=input("enter list values")


print(list1)


In [ ]:
mat=np.array(list1)
print(mat)

### Write a Python program to create a null vector of size 10 and update sixth value to 11

In [ ]:
import numpy as np

In [ ]:
vc=np.zeros(10)

In [ ]:
vc

In [ ]:
vc[6]=11

In [ ]:
print(vc)